### ISSUE TITLE
2 Colors

### ISSUE THREAD

**Issue by H4K0N42** [veebch/hometime#28]
I think I have a good idea but I don't know how to implement it. When an Event is active, you cannot see the progress of the Event.
In my case I chose to set events in the breaks and not the Lessons.

Here is my idea:
We make a progress bar for the whole day in (0, 0, 10) and a second progress bar for the Event in (0, 10, 0). So when a Event is active, the two bars are layerd over each other. When a Pixel is used by both, it should be (0, 10, 10).
When this mode is enabled, events should not be marked on the bar, when none is active.

I hope you like this idea, just implement it when you want, no need to do this soon.
If you don't like it, close this issue.

**Comment by veebch** [comment]
I like that idea! 

I'd thought about somehow 'layering' information, because 'how far through the event are we?' is a thing that I wonder too. I'd thought about the progress bar measuring the progress through individual events, but I also like glancing at it to see if there are other upcoming events. 

Just to make things a bit more complicated, some people use diffusers for the light, which makes colour information less clear. 

The most 'simple' idea I can think of is a secondary display the shows a 'percentage through day' and when appropriate a 'percentage through event', or a countdown timer, or something.

How people use their bar shapes how they might add tweaks such as this. 

I'll leave this open while I think about it, hopefully others will chip in too.

**Comment by H4K0N42** [comment]
Only thing that is missing is a function that sets for every pixel the array eventprogress[] if the "eventprogress" has reached that pixel

I will not make a pull request, but here is the code for the overlay:
```python
def draw_overlay(np):
    try:
        color = barcolourlist[3]
    except:
        color = [barcolourlist[0], eventcolourlist[0]]                  # Example: [(0, 100, 0), (0, 0, 100)]
        color = tuple(map(lambda y: sum(y) / int(len(y)), zip(*color))) # Get average of tuples: (0, 50, 50)
        color = tuple([int(2*x) for x in color])                        # Multiply tuples by two for same brightness: (0, 100, 100)
    
    for i in range(n):
        if eventprogress[i] == True:
            if np[i] == barcolourlist[0]:
                np[i] == color
            else:
                np[i] == eventcolourlist[0]
```

**Comment by H4K0N42** [comment]
I have added a Draft (#29), please check logic before merging.
